"""empty message

Revision ID: 02c0a626f987
Revises: None
Create Date: 2016-08-28 18:17:45.996602

"""

# revision identifiers, used by Alembic.
revision = '02c0a626f987'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('concert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('headliner', sa.String(length=80), nullable=True),
    sa.Column('supports', sa.Text(), nullable=True),
    sa.Column('age', sa.String(length=80), nullable=True),
    sa.Column('cost', sa.String(length=80), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'time', 'headliner')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concert')
    op.drop_table('venue')
    ### end Alembic commands ###
