"""empty message

Revision ID: c5ab2c348934
Revises: 02c0a626f987
Create Date: 2016-08-29 08:25:05.696000

"""

# revision identifiers, used by Alembic.
revision = 'c5ab2c348934'
down_revision = '02c0a626f987'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concert', sa.Column('created_at', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concert', 'created_at')
    ### end Alembic commands ###
